Issue # 1 - Make Publication listing page Tripal 3 compatible
UofS-Pulse-Binfo/kp_views pull request #2
Opened 2018-09-13 15:02 UTC by reynoldtan

Make publication listing page Tripal 3 compatible. It uses field: citation that contains author, title and year information instead of using field: author and field: title separately. This is due to some fields in views, including title and author return empty.

Layout of every item shows citation information (authors, title and year) in a paragraph form followed by a more information link. In Tripal 2 version, The title is a link followed by authors and year published aligned right. In addition, search criteria only shows year as option.

NOTE: update layout when title and author fields in views become available.

2018-09-27 21:30 UTC, laceysanderson requested changes
This view is missing many of the filter criteria that were on the original search. Is that because they don't work?

PS. It took me awhile to test this PR because I couldn't find the view. It turns out the old view needs to be disabled before this one will show up so that should be included in a testing section. When you reply, could you update the PR to match the new template here: https://github.com/UofS-Pulse-Binfo/KnowPulse/issues/45#issuecomment-425236014

2018-09-28 20:55 UTC, reynoldtan commented
**Issue # 1 - Make Publication listing page Tripal 3 compatible** 
To make publication listing page Tripal 3 compatible, I have created a new structure/view and setting the show option to publication. Further configurations required adding of fields entity id and citation. On the code level, I have exported this view and pasted the code into kp_defaultviews_uofs_publications() in kp_views_uofs_resarch.misc.inc template of KP_Views.

NOTE: Ideally, authors and title should be included in result but these fields returned **always empty value** and the only field that actually contained relevant info was the citation. Citation carry title, authors and year, concatenated into a single text value. 

##Metadata
Make Tripal v3 compatible
[https://github.com/UofS-Pulse-Binfo/kp_views/issues/1]

- [X] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

##Description
@see general summary above.
The "More Information" link is a rewrite result of rewriting from entity id to a link titled "More Information" (please see settings for entity id field in Drupal views panel).

##Dependencies
no dependencies

##Testing
- [ ] I tested on a generic Tripal Site
- [X] I tested on a KnowPulse Clone
   on dev/A
- [ ] This PR includes automated testing 

To test: 
Click the "More Publications" link on top right of Publications slideshow in the homepage of a KP Clone or use the link clone/research/publications. Click more information to access full details of the publication (leads to a fresh new publication page, Tripal 3 compaatible) and use the search criteria to filter list based on title, author and/or year published.

My first PR to use the format... am I the first too? I hope I complied :)

2018-09-28 21:26 UTC, laceysanderson commented
Looks pretty good :-)

I know actually including the fields returned blank information but can you try adding filter criteria to the view and test whether it filters correctly?

2018-09-28 21:32 UTC, reynoldtan commented
Yes, I added author and title criteria in addition to year which was the only search criteria on previous PR. Tested and they work.

2018-10-04 21:51 UTC, laceysanderson requested changes
You are missing the year...
<img width="1074" alt="screen shot 2018-10-04 at 3 48 50 pm" src="https://user-images.githubusercontent.com/1566301/46505106-38dd3d80-c7ed-11e8-830e-c97c80829f4c.png">

Also, rather then the "more information" link, lets just make the entire citation a link to the publication page. Much better aesthetically and more intuitive I think?

2018-11-26 18:40 UTC, reynoldtan commented
![screen shot 2018-11-26 at 12 37 23 pm](https://user-images.githubusercontent.com/15472253/49034660-34dbf500-f178-11e8-89fd-c5addddba6c9.png)


Revised publications page

2018-11-26 20:05 UTC, laceysanderson commented
Changes look good 👍 However, I just noticed that the view isn't sorted by publication year. It should be sorted to show the most recent publications first.

2018-11-26 20:28 UTC, reynoldtan commented
It is now sorting by year

2018-11-26 20:54 UTC, laceysanderson approved these changes
Perfect 👍 

NOTE: The old Tripal2 view needs to be deleted in order for this one to be seen.

2018-11-26 20:58 UTC, merged